### ISSUE TITLE
Apply hair particle modifier

### ISSUE THREAD

**Issue by momojohobo** [Moguri/blend2bam#12]
A way to set a lot of random objects in a scene is by using a hair particle emitter. An option to have them automatically applied by blend2bam would be great.

**Comment by Moguri** [comment]
Do you have an example blend file you can supply? I believe blend2bam should already be applying modifiers.

**Comment by momojohobo** [comment]
[trees.blend.zip](https://github.com/Moguri/blend2bam/files/3121624/trees.blend.zip)
