### ISSUE TITLE
Blender Binary not found

### ISSUE THREAD

**Issue by ConstantinosM** [Moguri/blend2bam#27]
Hello!

I am quite new to the "world of graphics" and I am trying to convert a very simple blender file (just a floor and a wall mesh without any textures or anything) to bam. I get an error from `subporcess.py`:

`FileNotFoundError: [Errno 2] No such file or directory: 'blender': 'blender'`

I used: `blender2bam Maze.blender Maze.bam` 
I am on Mac. From the files of the blender2bam it seems that bpy is being imported. Do I need to build Blender from source? I have just the app (v2.82a) in my Applications folder (I even included it in the command above but it didn't work). Could anyone help me identify what I am doing wrong?

Thanks in advance!

**Comment by Moguri** [comment]
I thought I had this documented, but apparently not: `blend2bam` requires Blender to be on the system. If Blender is findable in an appropriate `PATH` environment variable (i.e., running `blender` on the command line works), then there isn't anymore setup that's required. If Blender is not on the `PATH`, `blend2bam`will not be able to find it automatically. Instead, use the `--blender-dir` flag to let `blend2bam` know where to find Blender.
