### ISSUE TITLE
How can I mark and export animations?

### ISSUE THREAD

**Issue by IlyaFaer** [Moguri/blend2bam#30]
Previously I've been using YABEE, in which I've been marking animations with names and start/end frame numbers. Now I'm using blend2bam, and I'd like to do armature animations, but I didn't find any tutorials of how to name it, mark start and end, and then export it.

**Comment by Moguri** [comment]
For 2.7x, all actions should just export automatically. For 2.8+, blend2bam uses Blender's builtin glTF exporter, which requires [being more explicit about which actions to export](https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#animation). I haven't tried the "stash the action" option, but I do know that using the NLA editor works (just add a track for each action you'd like to export).

**Comment by IlyaFaer** [comment]
@Moguri, seems to me, that's it. Thanks!
I think, it'll be good to mention this in docs with a link to Blender's tutorial about actions and how to use them in our Panda3D case. You know, for newbies.
