### ISSUE TITLE
Imported models are blue-ish

### ISSUE THREAD

**Issue by adriancalavie** [Moguri/blend2bam#32]
Models in blender are ok, textured and all, but when I import them and open the .bam using panda3d viewer, the models look as if a UV lightbulb would be above them.

**Comment by Moguri** [comment]
Which version of Blender are you using and which pipeline (EGG or glTF)? If you're using Blender 2.8 and glTF, then you might be running into issues with using PBR materials with Panda's auto shader.

**Comment by adriancalavie** [comment]
Yeah, I was using Blender 2.8 and the glTF pipeline. In the end I scraped that idea and I imported my models as .obj (I found out that Panda3d now supports .obj). No problems since
