### ISSUE TITLE
Exporting file results in blender error

### ISSUE THREAD

**Issue by Clockwork-Muse** [Moguri/blend2bam#47]
Blender is throwing an error while still successfully exporting a model:
```
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Blender 2.91.0 (hash 0f45cab862b8 built 2020-11-25 08:51:08)
Warning: Falling back to the standard locale ("C")
Read prefs: /home/someuser/.config/blender/2.91/config/userpref.blend
found bundled python: /blender/2.91/python
srcroot: /panda/models/
Exporting: ['/panda/models/untitled.blend']
Export to: /tmp/
Read blend: /panda/models/untitled.blend
Converting .blend file (/panda/models/untitled.blend) to .gltf (/tmp/untitled.gltf)
Traceback (most recent call last):
  File "/blender/2.91/scripts/addons/io_scene_gltf2/__init__.py", line 76, in on_export_format_changed
    operator = sfile.active_operator
AttributeError: 'NoneType' object has no attribute 'active_operator'
File "/blender/2.91/scripts/addons/io_scene_gltf2/__init__.py", line 73, in on_export_format_changed
'/blender/2.91/python/lib/python3.7/site-packages/libextern_draco.so' exists, draco mesh compression is available
00:42:58 | INFO: Starting glTF 2.0 export
00:42:58 | INFO: Extracting primitive: Cube
00:42:58 | INFO: Primitives created: 1
00:42:58 | INFO: Finished glTF 2.0 export in 0.010235786437988281 s
```

... I'm not entirely sure that this is a blend2bam issue, but it may be due to _how_ the export is being called.  The error is not generated when the export is done manually from inside blender.

This is happening when just loading a default file.

Blender 2.91
panda3d-blend2bam 0.17
panda3d-gltf 0.11
[repro.zip](https://github.com/Moguri/blend2bam/files/5656136/repro.zip)

**Comment by AndyMender** [comment]
Running into the same issue on my Arch Linux installation:
Blender 2.91
panda3d-blend2bam 0.18
panda3d-gltf 0.12

There is a DracoPy package in PyPi, but it doesn't provide the missing SO file: https://pypi.org/project/DracoPy/

Still, blend -> bam conversion seems to work for a basic Blender cube object:

![cube_bam_loaded](https://user-images.githubusercontent.com/15969405/103794417-f8607000-5044-11eb-9dbd-cb383d5b3512.jpg)

**Comment by Moguri** [comment]
Looks like using the glTF exporter in Blender in background mode is broken: https://developer.blender.org/T83188

There really isn't anything blend2bam can do about this situation, so it seems that blend2bam will not work with 2.91 until this is fixed upstream.

**Comment by Moguri** [comment]
I should have paid a bit more attention to this. blend2bam still works, it just outputs that extra error. That error does not prevent blend2bam from working correctly. So, this will just be a quick of running blend2bam on 2.91. This has been fixed upstream so newer releases of Blender will not display this error. I am closing this as "wont't fix".
