### ISSUE TITLE
Can't get pixel shaders to work with exported models

### ISSUE THREAD

**Issue by Clockwork-Muse** [Moguri/blend2bam#48]
Attempting to load models and turn on auto shading isn't working.  The result is a black object, even with lights added manually to the scene (or things like a normal map added to the model manually later).  The model does load and has a visible color texture without enabling auto shading:

![image](https://user-images.githubusercontent.com/5569508/101424297-b1e5ed00-38af-11eb-97c2-1ebfd601cd1d.png)

... but simply calling `render.setShaderAuto()` results in a black object:

![image](https://user-images.githubusercontent.com/5569508/101424366-dd68d780-38af-11eb-9797-e0f904658223.png)

The system does support pixel shaders - the sample bump mapping program works.  However I can't get exported models to work.  Manually exporting to a .bam file doesn't affect things.

... I've been assuming that I could do a simple setup inside of blender for this: 
![image](https://user-images.githubusercontent.com/5569508/101425940-de4e3900-38b0-11eb-9e81-953c0541cf32.png)

... and indeed the resulting gltf does include a reference to the normals file, but nothing shows on screen...

[repro.zip](https://github.com/Moguri/blend2bam/files/5656220/repro.zip)

**Comment by rdb** [comment]
I think the problem is that there are no binormals and tangents being exported.

For the record, the recommendation is to use simplepbr instead of the auto-shaders, since simplepbr is designed to work best with blend2bam:
https://github.com/Moguri/panda3d-simplepbr

**Comment by Clockwork-Muse** [comment]
Ah, yes, because bi-tangents are not exported in gltf (and the gltf importer is not currently converting them): https://github.com/Moguri/panda3d-gltf/issues/69

**Comment by Clockwork-Muse** [comment]
Out of curiosity attempted to just add the bitangents after load (since it should be just the cross product), and get this (not bad):

![image](https://user-images.githubusercontent.com/5569508/101676264-cd680980-3a0f-11eb-932e-f18c63675322.png)

... turning on shadows gives me a weird moire pattern, though:
![image](https://user-images.githubusercontent.com/5569508/101676394-fab4b780-3a0f-11eb-8b01-7f9f79a26f6b.png)

... I'm getting the same thing out of `simplepbr`, though, so there's undoubtedly something up with my model setup

**Comment by rdb** [comment]
That's related to shadowing.  The problem is that by default, Blender has double-sided rendering enabled on your materials.  Tick back-face culling on your materials and the problem will go away.

**Comment by Clockwork-Muse** [comment]
Ah, hm.  Yes that helps, but doesn't completely fix the issue (this particular shot is via `simplepbr`).  I'm still getting the pattern in areas on the opposite side of the object from the light:
![image](https://user-images.githubusercontent.com/5569508/101693484-82a5bc00-3a26-11eb-857f-c51fa64bab31.png)

> Tick back-face culling on your materials and the problem will go away.

Is there a "how to get stuff setup in Blender" how-to somewhere?  The model-export section of the panda manual doesn't mention this.

**Comment by rdb** [comment]
Ah, yeah, exaggerated normal mapping can still cause shadow acne to show up at the boundary.  There are some ways to solve that by biasing depth value lookups in the shader (or using a depth offset attribute).

There's no such guide at the moment.  We really ought to create one.

**Comment by Moguri** [comment]
Is there any remaining blend2bam work/issue here other than "create docs"?

**Comment by Clockwork-Muse** [comment]
Just "create docs", I think.

**Comment by Moguri** [comment]
Docs started [here](https://github.com/Moguri/blend2bam/blob/master/docs/conversion-guide-gltf28.md). Feel free to file new issues or submit PRs for anything you notice is missing or could be improved.

**Comment by Clockwork-Muse** [comment]
@Moguri - Thanks!
