### ISSUE TITLE
Passive physics objects are exported as intangible

### ISSUE THREAD

**Issue by Clockwork-Muse** [Moguri/blend2bam#53]
... but passive physics objects in blender aren't intangible, so this behavior is surprising.  Worse, this behavior is not documented or otherwise called out, making it hard to discover this as the cause.

Perhaps a better option is to set tangibility based on whether the physics object is part of _any_ collision group

**Comment by Moguri** [comment]
#46 already exists for discussing how to best handle physics/collisions exporting (including intangible). Please join the discussion there. Closing this issue as duplicate.
