### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by Epihaius** [Moguri/blend2bam#64]
Hi,

Is it at all possible to run `blend2bam` with a portable version of Blender (i.e. extracted from a .zip file into a arbitrary directory)?

With Blender residing in `D:\Portable\blender-2.91.0-windows64\`, I call `blend2bam` like so:

```
blend2bam my_scene.blend my_scene.bam --blender-dir "D:\Portable\blender-2.91.0-windows64\" --blender-bin blender.exe
```

This leads to the following error:

```
Traceback (most recent call last):
  File "d:\panda3d-1.10.10-x64\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\panda3d-1.10.10-x64\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Panda3D-1.10.10-x64\python\Scripts\blend2bam.exe\__main__.py", line 7, in <module>
  File "d:\panda3d-1.10.10-x64\python\lib\site-packages\blend2bam\cli.py", line 218, in main
    if not blenderutils.blender_exists(args.blender_dir, args.blender_bin):
  File "d:\panda3d-1.10.10-x64\python\lib\site-packages\blend2bam\blenderutils.py", line 39, in blender_exists
    is_blender_28(blenderdir=blenderdir, blenderbin=blenderbin)
  File "d:\panda3d-1.10.10-x64\python\lib\site-packages\blend2bam\blenderutils.py", line 60, in is_blender_28
    version = get_blender_version(blenderdir=blenderdir, blenderbin=blenderbin)
  File "d:\panda3d-1.10.10-x64\python\lib\site-packages\blend2bam\blenderutils.py", line 52, in get_blender_version
    output = subprocess.check_output([binpath, '--version'])
  File "d:\panda3d-1.10.10-x64\python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "d:\panda3d-1.10.10-x64\python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "d:\panda3d-1.10.10-x64\python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "d:\panda3d-1.10.10-x64\python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied
```

Running the command console as administrator makes no difference.

If Blender really does need to be installed, no problem, feel free to close this issue then. My reason for using portable versions of Blender is to have the possibility to compare older and newer versions by having them side-by-side.

**Comment by rdb** [comment]
What utility did you use to extract Blender from the zip file?

Are you able to run blender.exe from the command-line (try the `--version` flag)?

**Comment by Epihaius** [comment]
> What utility did you use to extract Blender from the zip file?

That would be 7zip.

> Are you able to run blender.exe from the command-line (try the --version flag)?

Only from within the directory I unzipped it to. Not surprising, since I haven't added any Blender version to the system PATH. (And I don't think it makes sense to do so as I have multiple versions.)

**Comment by Moguri** [comment]
You do not need to specify `--blender-bin` since `blender.exe` will be what `blend2bam` will be looking for by default. What you have set might actually make `blend2bam` look for `blender.exe.exe`, which would be bad. The `--blender-dir` flag is intended for these types of situations, and I have no idea why `blend2bam` would care if the binary is "installed" to the system or not. It would be useful to know the path/binary `blend2bam` is trying to open/execute to see if something got messed up (e.g., with Windows vs Linux paths).

**Comment by Epihaius** [comment]
>What you have set might actually make `blend2bam` look for `blender.exe.exe`, which would be bad.

Ah, adding the ".exe" extension seems to have been the problem. Thanks, it works now.

But may I just say that I do not find it obvious that an extension is added automatically. Also, if it's your intent to make life easier for the user by not having to specify it explicitly, wouldn't it make sense to handle the case where it *is* manually added as well? (Preferably by replacing any extension in the given binary name string as needed, rather than throwing e.g. an AssertionError.)

Alternatively, please make it clear in the documentation that explicitly adding an extension is not only unnecessary, but even prohibited.

By the way, why isn't there just a single `--blender-bin-path` flag instead of separate `--blender-dir` and `--blender-bin` flags?
Specifically, is there a use case where one would set `--blender-bin` without setting `--blender-dir`?

Since it seems fine to use a portable (vs. "installed") version of Blender with `blend2bam`, may I then suggest to rephrase the following in the documentation:

> `blend2bam` also requires that Blender is installed.

to something like this:

> `blend2bam` also requires Blender, either installed or "portable" (.zip).

Thanks!

**Comment by Moguri** [comment]
`--blender-bin` is useful when multiple Blender binaries are available on the system PATH (e.g., `blender` and `blender-2.7`). It was recently implemented, and I had only tested it on Linux, which is why I missed the '.exe'. I fixed this and updated the readme wording.
