### ISSUE TITLE
[I want to directly support/donate] Cub3D.apk == Can Play Panda3D Samples on Android Phone

### ISSUE THREAD

**Issue by LukongGITHUB** [Moguri/blend2bam#67]
I don't if you got my message and I can't find any issues with Cub3D in closed or open. I was simply trying to say that if your able to make a plugin that allows people to export to panda3D as Folder [Not .BAM] then people can place that folder where Cub3D.apk can find it and play it then package their Games into APKs.
The problem is finding the devs for Cub3D -u2600inventions- and collabrating with them.
https://m.apkpure.com/cub3d-python-3-6-3d-programming-ide/com.u2600inventions.cub3d
- I Tested out the problems with Export'g your Plugin -or someone elses- and some problems are Export2Bam doesn't run in Cub3D, but the project folder does and pman or pygame has to be removed from the main.py script
- Not all Panda3D samples can run, but most do, but I believe in order to truly make BGE2BAM the Logic Bricks Codes would need to be re-interpreted into Panda3D Scripts or Assigned Panda3D Bricks [Like Motion.act == Motion.actpan]...and that means someone would have to build Panda3D Bricks out of Python Code [which is unfair and a lot of work]

I was trying to say that if you get Blend2Bam work'g as I don't use the Engine-side [.BAM] of you Plugin, but the Export Project [Folder]
- I hoped I could use Blender2.79's Game Engine due to the Logic Editor Easiness, but I see that Blender 2.79 isn't support as much [I have my own idea for Better/Simpler/Efficient Logic Editor...based on my understand'g of it 'ITON']
- If its even possible for the NeuroBGE [Pro-Py], UPBGE [Pro-C] & MakeHuman [Pro-Py] to work together...people can put games out on the biggest platform while give'g a cut to you devs [I know 30% for Platform + 10-30% for Code Devs = 60-40% left for Game Devs...but technically you deserve a lot cause your getting the games out their and maybe a deal w/fee-breaks [pre/post gross/net/filetax profit] & large payouts when when games make it big like 30% at 5-100K, 20% at 200-750K, 10% at 1-3mil, 10% at 5-10Mil, 20% of 15-20Mil, 30% at 30-50Mil]

**Comment by Moguri** [comment]
Are you asking for help getting pman working with this Cub3D tool? I do not know what blend2bam offers if you do not want BAM files. The other half of blend2bam is just exporting blend files as either glTF or EGG. In any case, I do not see anything actionable in this issue. If you are running into specific issues, please feel free to create new issues.

**Comment by LukongGITHUB** [comment]
I don't know if you got my reply due to gmail not showing me that I've replied.

1. Why close the issue then ask me to create a new issue?
- Did you mean an Actionable Issue? Like fixing how the Project Folder
can only be created once then Blender needs to be re-installed in
order to work...I think you fixed that

2. Its not about the BAM its about the Project folder -the other half
of the Plugin- that Cub3D can use, but of course that leaves all the
code and game in the open

3. The Action is to collaborate with good Python Devs like UPBGE,
Armory, NeuroBGE & MakeHuman to make a Logic Brick to Panda3D system
then work towards Cub3D so Devs can have access to the Android Market
[30% = Google Fee, 10-30% = BGE2CUB3D Devs & 60-40% = Game Devs]
- As your plugin is a Mesh Converter, but if your able to code Logic
Bricks to Panda3D Code then people can Dev Panda3D games easier then
if the Project Folder or make a 3rd export [BAM, Project Folder &
Pro-Cub3D Project Folder]
- I removed a little of code from the main.py and got it to run [On
Android Emulation], but I have to redo to see what I did, though I
remember removing pman or pygame from the code cause Cub3D may not
have those repositories

**Comment by rdb** [comment]
I have no idea what you're on about regarding project folders, but Cub3D was pulled from the Play Store a long time ago, why not focus your efforts on Panda3D's official Android port, which works just fine with .bam files?
https://discourse.panda3d.org/t/deployment-for-android/28226

**Comment by LukongGITHUB** [comment]
I didn't know this, but Cub3D was put back on Google Play Store as I
was able actually find it when I needed the expert edition I paid for.

Maybe I mistook your plugin for another.
There are 1-3. Its should be the one that can Export to Bam, Panda3D
Engine & makes a project folder.
Thanks for Link. Though you can still get the app...I think I gave you
the link in that closed issue...do you want it again and test the
difference?

- Also it requires Python 3.8, while both Cub3D & Blender 2.79 [BGE]
uses Python 3.6-7 [But Can lower Python work with]
- Cub3D actually works out the box...but hey okay...pulled app vs
complex building...I am terrible when it comes to coding
anyways...hence I love the Logic Brick Editor

Thanks I guess trying to avoid code is avoid develop'g

**Comment by rdb** [comment]
I'm glad that you found an archived copy of Cub3D and that it works for you, but it is no longer being updated by the original developer, and we can't update or modify it because we don't have the source code, since it's a closed-source product.  That makes it a dead end as far as I'm concerned, however user-friendly it may be.

**Comment by LukongGITHUB** [comment]
LOLOLOL I never said to update it. I said if you could modify your own
code to work just like the Panda3D samples that your plugin should
work like.
Closed-source product doesn't mean useless as it far surpasses a label
of 'Beta' or 'Abandonware' let alone Dead...it not being on the Google
Play makes it more of inside secret.

Quiz: Have you tried using the App at all with some of the Panda3D Samples?
- You could use it to test your plugin unless you prefer going thru
the steps the link you gave me

Quiz: Is your plugin finished for what its trying to do [Convert Blend
to Panda3D Models]?

**Comment by LukongGITHUB** [comment]
Sorry I might me talking to the wrong person. I am looking for the
'Project Folder w/main.py ' Plugin as their are other Blender to
Panda3D plugins.

**Comment by LukongGITHUB** [comment]
I see what you mean by start another issue I think I started an issue
in the wrong plugin

**Comment by LukongGITHUB** [comment]
https://pythonlang.dev/repo/moguri-blenderpanda/

Cub3D, your plugin, Panda3D & Blender all have the same or similar
python depencies 3.5-7
