### ISSUE TITLE
Object Animation ?

### ISSUE THREAD

**Issue by Annakan** [Moguri/blend2bam#71]
Hello,
First Thanks a lot for this tool and the other that breath a lot of life into Panda3D.

I saw that "object animation" where not supported (and of course I need them for my pet project :))  and was wondering were the issue came from ? is it a "I did not have time to implement this" or is it a "Panda does not support it"

Panda's Actor class is quite "obsessive" about having a "Character" node in the model and refuse to load any mesh without one. These nodes seem to only be created when there is skinning / rigging done in Blender, correct me if I am wrong.

So I was wondering if it is that Panda only support animation though actor and that actors are supposed to be "rigged characters" and there is no way around this ?
Or would it be possible to load animation into a regular mesh and have it play and it is "only" an importer problem ?

I am new to Panda3D and 3D game programming in general but not to Python so I am open to pointers if something could be done or tried with my limited knowledge.

Thanks a lot for your time.

**Comment by rdb** [comment]
Related issues:
Moguri/panda3d-gltf#26
panda3d/panda3d#457

**Comment by Annakan** [comment]
Thanks a lot, sorry I did not find them myself.

So it is basically a panda3D limitation that could be overrided by some clever import trickery with some side effects ... 

Noted thanks :)
