### ISSUE TITLE
Shape Keys don't get exported

### ISSUE THREAD

**Issue by staylazy-studios** [Moguri/blend2bam#72]
I've created a new model and exported one with gltf and one with blend2bam. the gltf version works but not the bam version.

the code:
```python
from direct.showbase.ShowBase import ShowBase
from direct.actor.Actor import Actor
from direct.interval.LerpInterval import LerpPosInterval

class ShapeKeys(ShowBase):
    def __init__(self):
        super().__init__()

        self.cube = Actor("box2.gltf") # this works
        #self.cube = Actor("box2.bam") # not this
        self.cube.reparentTo(self.render)
        print(self.cube.listJoints())

        self.joint = self.cube.controlJoint(None, "modelRoot", "Key 1")

        i = LerpPosInterval(
                self.joint,
                5,
                (1, 0, 0),
                blendType='noBlend',
                name="cube interval"
            )
        i.start()

ShapeKeys().run()
```
the blend file is a newly created version 3.3.1 model with Shape keys `Basis` and `Key 1`
[box2.zip](https://github.com/Moguri/blend2bam/files/10098219/box2.zip)

![image](https://user-images.githubusercontent.com/108659753/204133368-1c15d787-9342-42d0-9eb0-e4f58cca5669.png)

Entikan on Discord pointed out that it could be because of blend2bam not supporting the new "Shape Keys" tick on gltf export
![image](https://user-images.githubusercontent.com/108659753/204133735-f8df1c0b-4153-40a7-a914-489e512703a3.png)

**Comment by Moguri** [comment]
This option is checked by default, so I do not believe that is the issue. However, it seems that the Apply Modifiers option breaks shape keys. I have not had a chance to look at the file itself, but does the object in question have modifiers?

**Comment by staylazy-studios** [comment]
@Moguri 
No, it doesn't have any modifiers applied.
It's just the default cube with the default shape key 'Basis' and 'Key 1' which looks like:
![image](https://user-images.githubusercontent.com/108659753/204744910-5eb4bd71-0405-4479-bb02-7bf424e08357.png)

**Comment by Moguri** [comment]
I did some digging, and it looks like some change in Blender 3.3 broke shape key export for blend2bam. I have some ideas for how to fix it. In the meantime, you can use an older version of Blender as a work-around.

**Comment by staylazy-studios** [comment]
Oh, okay. I tried it with 3.2.2 and it worked!
Thanks for your help!

**Comment by Moguri** [comment]
I have pushed a potential fix to `master` if you'd like to give it a try in your workflow.

**Comment by Moguri** [comment]
Marking as resolved.
