### ISSUE TITLE
Tobspr's RP support please？

### ISSUE THREAD

**Issue by SoNewBee** [Moguri/blend2bam#76]
We really need a tool which can export models,materials,bones&deforms,animations and etc. to tobspr's RP.
Blend2bam is a really brilliant tool for panda3d,and it provided functions which can work with PBR comfortably,so can we add the functions above？
It will make panda3d more powerful.

**Comment by Moguri** [comment]
What is currently broken? I know RP has its own lights, so support would have to be added for those. RP is also particular about texture slots, but it really should be updated to use the semantic texture slots.

**Comment by rdb** [comment]
Yeah, I think this issue should be filed on RP to add support for blend2bam, or particularly, semantic texture slots.

**Comment by QuanyiLi** [comment]
Ah, I need this feature as well.  RP's texture slot requirement prevents me from loading models correctly. Look forward to your update! Thanks

**Comment by SoNewBee** [comment]
> What is currently broken? I know RP has its own lights, so support would have to be added for those. RP is also particular about texture slots, but it really should be updated to use the semantic texture slots.

Yes,all above you mentioned.
I don't think RP will be updated...
It has been a long time since the last update.
So I can only hope on blend2bam.

**Comment by QuanyiLi** [comment]
@SoNewBee Hey, buddy. I solved this problem by 
1. loading the gltf model to blender 
2. saving as ```xyz.blend``` 
3. converting ```xyz.blend``` it to ```xyz.egg``` with this tool: using https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/blob/master/blend2egg.md

**Comment by SoNewBee** [comment]
> @SoNewBee Hey, buddy. I solved this problem by
> 
> 1. loading the gltf model to blender
> 2. saving as `xyz.blend`
> 3. converting `xyz.blend` it to `xyz.egg` with this tool: using https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/blob/master/blend2egg.md

OK，thanks.

I will try it.
And...Do you know how to use particle system in RP？
I didn't find anything about particles in the wiki of RP.

**Comment by QuanyiLi** [comment]
No, all I know is how to turn on/off the cloud, lol. I am a newbie to RP.

**Comment by Moguri** [comment]
Closing this since blend2bam is not going to add support for RP's current texture slots. If/when RP supports semantic texture slots, then we can consider add support for things like RP's lights.
