### ISSUE TITLE
Support glTF exporter texture packing

### ISSUE THREAD

**Issue by rayanalysis** [Moguri/blend2bam#78]
Below is an example of a contemporary Principled BSDF texture setup in Blender 3.2 (from a project of mine):

![image](https://user-images.githubusercontent.com/3117958/235326453-7c19df3c-f4d0-424c-a428-8f9d5733ff0e.png)

As stated by Moguri recently:

> blend2bam currently expects a single ORM map and cannot leverage the texture packing provided by the glTF exporter. This is mostly due to being originally built for a much older gltf exporter that pre-dates the current one. It’s a long standing todo, and I might have to drop 2.7x support to fix it.

When the above model is exported via blend2bam, several texture maps are dropped and the resulting model does not render correctly. The only alternative is to export directly to .gltf which cannot be directly packaged into a Panda3D executable. Or, one can remake the textures into a single ORM map, which is not particularly straightforward or elegant for a number of us I imagine.

I would really like to see support for the glTF exporter texture packing added to blend2bam. This would allow a seamless workflow from Blender 3 to development and executable production, particularly via https://discourse.panda3d.org/t/blender-3-0-bam-exporter-addon/29313

If there is anything I can do to help, or if we'd like to create a branch to prototype this support, let me know.

**Comment by Moguri** [comment]
Can you please check to see if a6fc30ea14ceedacd764ff4567ea19b7a5883645 resolves this issue?

**Comment by Moguri** [comment]
Could you please provide an example blend file and textures? Packed textures would work fine so you only have to upload one file.

**Comment by rayanalysis** [comment]
I'm afraid the latest versions from source still throw an error, albeit a slightly different one:

01:34:31 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.

Warning: Failed to find image data for Metal041A_2K_NormalGL.png, skipping
Warning: Failed to find image data for Metal041A_2K_Color.png, skipping
Warning: Failed to find image data for Metal041A_2K_Roughness.png, skipping

Blender quit

I believe this would happen for any of my files, this one in particular is the arena sample program handgun with some new textures applied.

**Comment by Moguri** [comment]
I converted the gun from the arena sample with `--textures copy`, and it looks like it is working correctly for me using the current `master` version of `blend2bam`.
