### ISSUE TITLE
Blender 3.6.0 animations not loading or playing properly

### ISSUE THREAD

**Issue by IzzyBoris** [Moguri/blend2bam#84]
## Description
Rig animations I've created in Blender 3.6.0 seem not to fully load and don't play correctly. Models converted using Blender 3.3 LTS work fine.

In 3.6.0 this happens whether I load as a .blend file or export as glTF .glb files. The mesh does move slightly but the animation reports only 2 frames (where there should be 12 in the test model). Increasing the number of frames in the Action seems to slow down the animation, like Panda3d is trying to stretch the same number of frames (2?) over a larger number of displayed frames.

If the .blend is converted using Blender 3.3 LTS, or exported as glTF using 3.3, animation works fine.

The 3.6 .blend file also reports "No animation" when opened with pview.

## Steps to Reproduce
* Extract test.zip and run test.py which loads and displays a test*.blend model and tries to loop the "wave" animation.
  * test.zip includes the same model in Blender 3.3 LTS and 3.6 formats, and .bam files converting each of these using both Blender 3.3 LTS and 3.6.0.

## Environment
 * Operating system: Windows 11
 * System architecture: Intel I7 nVidia 3060
 * Panda3D version: 1.10.13.post1
 * Installation method: pip
 * Python version (if using Python): 3.11
 * Compiler (if using C++): N/A
* Blender 3.6.0

![blenderbox](https://github.com/Moguri/blend2bam/assets/137025642/b5c2aafb-127a-4887-904d-20ea72d47079)
![pandabox](https://github.com
[test.zip](https://github.com/Moguri/blend2bam/files/12113169/test.zip)
/Moguri/blend2bam/assets/137025642/69ee501c-653f-4a67-879d-984dac61c6d9)

**Comment by IzzyBoris** [comment]
Confirmed this seems to work now with Blender 3.6. Thanks!

**Comment by izzyboris** [comment]
So, not sure what happened, but I thought this was working after your fix yesterday, but today it doesn't seem to be (I'm seeing the same pre-fix behavior when using Blender 3.6).

However I've noticed that even exporting from Blender 3.6 to .gltf using the built-in exporter produces the same "2-frame" animation problem I've been seeing when loading them directly into gltf-viewer, taking blend2bam itself out of the loop entirely.

Attaching direct embedded .gltf exports from Blender 3.3 and Blender 3.6 of the same model in case they're helpful, but maybe my current issue is elsewhere?

Versions from pip list:
Panda3D           1.10.13.post1
panda3d-blend2bam 0.21 (pip install -e .[tests] from master branch)
panda3d-gltf      0.15.0
panda3d-simplepbr 0.10

[testcube-3.3-3.6.zip](https://github.com/Moguri/blend2bam/files/12188821/testcube-3.3-3.6.zip)
